### ISSUE TITLE
Implementar Cadastro em etapas

### ISSUE THREAD

**Issue by tonny-weslley** [tads-cnat/fretex#162]
O Cadastro de usuario e freteiro deve ser realizado em etapas, para aproveitar melhor o fluxo da aplicacao.
seguem aqui a orientacoes de execucao:
[ ] - Criacao de endpoint para verificar se o email ja esta em uso na aplicacao
[ ] - Implementar fluxo de Cliente
[ ] - Implementar fluxo de freteiro

**Comment by Lucas-Veras** [comment]
Finalizado
