### ISSUE TITLE
Definição de tecnologias do projeto

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/fretex#34]
Realizar estudo e definir tecnologia para desenvolver o front-end e back-end.

## Tempo previsto (em horas): 8h

`Para os integrantes responderem:`

**Tempo gasto (em horas):** 

**Complexidade (baixa | média | alta):**

**Qualidade (baixa | média | alta):**

**Comment by ItaloGSM** [comment]
Tempo gasto (em horas): 1h45min

Complexidade (baixa | média | alta): média

Qualidade (baixa | média | alta): alta
