### ISSUE TITLE
Revisar documento de visão

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/fretex#35]
Realizar a revisão do documento de visão colocando em formato **Markdown**.

## Tempo previsto (em horas): 8h

`Para os integrantes responderem:`

**Tempo gasto (em horas):** 

**Complexidade (baixa | média | alta):**

**Qualidade (baixa | média | alta):**

**Comment by ItaloGSM** [comment]
Tempo gasto (em horas): 2horas

Complexidade (baixa | média | alta): média

Qualidade (baixa | média | alta): alta
