### ISSUE TITLE
Criar glossário

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/fretex#36]
Iniciar o glossário do projeto.

## Tempo previsto (em horas): 2h

`Para os integrantes responderem:`

**Tempo gasto (em horas):** 

**Complexidade (baixa | média | alta):**

**Qualidade (baixa | média | alta):**

**Comment by MathewsDantas** [comment]
Tempo gasto (em horas): 45min

Complexidade (baixa | média | alta): Baixa

Qualidade (baixa | média | alta): Alta
