### ISSUE TITLE
Definir o caso de uso de validação da arquitetura

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/fretex#37]
Definir o caso de uso principal que servirá de teste para validar a arquitetura.

## Tempo previsto (em horas): 2h

`Para os integrantes responderem:`

**Tempo gasto (em horas):** 

**Complexidade (baixa | média | alta):**

**Qualidade (baixa | média | alta):**

**Comment by ItaloGSM** [comment]
Tempo gasto (em horas): 1hora

Complexidade (baixa | média | alta): media

Qualidade (baixa | média | alta):  alta
