### ISSUE TITLE
Escrever caso de uso de validação da arquitetura

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/fretex#38]
Descrever os caso de uso de validação da arquitetura em termos de fluxo principal, fluxos alternativos, pré e pós-condições, entre outros itens do modelo trabalhando na disciplina de APOO.

**Obs.:** Tratar o máximo de caminhos alternativos possíveis. Incluir as possíveis mensagens de erro que devem ser utilizadas para orientar usuários e desenvolvedores.

## Tempo previsto (em horas): 8h

`Para os integrantes responderem:`

**Tempo gasto (em horas):** 

**Complexidade (baixa | média | alta):**

**Qualidade (baixa | média | alta):**

**Comment by MathewsDantas** [comment]
Tempo gasto (em horas): 2 horas

Complexidade (baixa | média | alta): Média

Qualidade (baixa | média | alta): Alta
